version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - Herve-M
  ignore:
  - dependency-name: Vanara.PInvoke.Security
    versions:
    - 3.3.2
    - 3.3.3
    - 3.3.4
    - 3.3.5
    - 3.3.6
    - 3.3.7
