# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

trigger:
  branches:
    include:
    - master
    - develop
    exclude:
    - feature/*
    - fix/*

pr:
  branches:
    include:
    - develop/*
    exclude:
    - features/fix/*

pool:
  vmImage: 'windows-2019'

variables:
  solution: '$(Build.SourcesDirectory)/src/*.sln'
  project: '$(Build.SourcesDirectory)/src/**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Setup .NET Core SDK'
  inputs:
    packageType: sdk
    version: 3.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    projects: '$(project)'
    verbosityRestore: 'normal'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/src/CM/CM.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore --include-symbols --include-source --output $(Build.StagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Pack - Manager'
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/src/CM.Abstractions/CM.Abstractions.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore --output $(Build.StagingDirectory)'

- task: PublishPipelineArtifact@0
  displayName: 'Publishing artifact'
  inputs:
    artifactName: 'CM-build' 
    targetPath: '$(Build.StagingDirectory)'
