# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

trigger:
  branches:
    include:
    - master
    - develop
    exclude:
    - feature/*
    - fix/*

pr:
  branches:
    include:
    - develop/*
    exclude:
    - features/experimental/*

pool:
  vmImage: 'windows-2019'

variables:
  solution: '$(Build.SourcesDirectory)/src/*.sln'
  project: '$(Build.SourcesDirectory)/src/**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Setup .NET Core SDK'
  inputs:
    packageType: sdk
    version: 3.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(project)'
    verbosityRestore: 'normal'

- task: DotNetCoreCLI@2
  displayName: 'Build - Abstraction'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/CM.Abstractions/CM.Abstractions.csproj'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build - Manager'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/CM/CM.csproj'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack - Abstraction'
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/src/CM/CM.csproj'
    #arguments: '--no-build --no-restore --include-symbols --include-source'
    includesymbols: true
    includesource: true
    nobuild: true
    verbosityRestore: 'normal'
    
- task: DotNetCoreCLI@2
  displayName: 'Pack - Manager'
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/src/CM.Abstractions/CM.Abstractions.csproj'
    #arguments: '--no-build --no-restore'
    nobuild: true
    verbosityRestore: 'normal'
